language: java
jdk:
  - oraclejdk9
  - openjdk8
  - openjdk7
install:
  - mvn clean install -DskipTests=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
cache:
  directories:
  - $HOME/.m2
sudo: false
notifications:
  email: false
